---
# Source: calico/templates/calico-kube-controllers.yaml
# See https://github.com/projectcalico/kube-controllers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calico.fullname" . }}-kube-controllers
  labels:
    k8s-app: {{ include "calico.fullname" . }}-kube-controllers
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ include "calico.fullname" . }}-kube-controllers
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ include "calico.fullname" . }}-kube-controllers
      labels:
        k8s-app: {{ include "calico.fullname" . }}-kube-controllers
    spec:
      nodeSelector:
        {{- toYaml .Values.controllers.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.controllers.tolerations | nindent 8 }}
      serviceAccountName: {{ include "controllers.serviceAccountName" . }}
      priorityClassName: {{ .Values.controllers.priorityClassName }}
      containers:
        - name: calico-kube-controllers
          image: "{{ .Values.controllers.image.repository }}:{{ .Values.controllers.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controllers.image.pullPolicy }}
          env:
            # Choose which controllers to run.
            - name: ENABLED_CONTROLLERS
              value: node
            - name: DATASTORE_TYPE
              value: kubernetes
          livenessProbe:
            exec:
              command:
              - /usr/bin/check-status
              - -l
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /usr/bin/check-status
              - -r
            periodSeconds: 10
